### ISSUE TITLE
Add Update Raw or Update using in database.

### ISSUE THREAD

**Issue by NamelessHH** [sqlkata/querybuilder#159]
Can't see it in the documentation or in the examples so I don't know if theres a way to either pass in raw set parameters to an update or use the current way to change the value of a column based on what is there.

for instanstance

`
update [tablename] set displayindex=displayindex+1 where displayindex> 5
`

**Comment by jeremyalan** [comment]
Sorry, I realize this issue was closed a year ago, just wondering if "for now" implies that this functionality might be supported in a future update, and if it's being tracking anywhere outside of this issue.

I have a similar concern that is very common, as we need the ability to increment a "Version" column on records during an UPDATE, which is cumbersome to pre-fetch the value of this column for a single record, and appears to not be possible when updating multiple rows using a SELECT query.

Typical raw SQL might look something like:
```sql
UPDATE W
SET
   [IsActive] = 0,
   [Version] = [Version] + 1
   [VersionOn] = SYSDATETIMEOFFSET(), -- or engine equivalent
   [VersionBy] = @CurrentUser
FROM [Widget].[Widget] W
WHERE W.[IsActive] = 1
```

I see the work-around that was posted earlier for constructing the raw SQL, and passing it ad-hoc using `db.Statement(...)`, which I will look into for now, but I think it would be great to be able to pass a SQL expression as the value during an UPDATE.

Thanks!
