### ISSUE TITLE
.NET Standard 2.0 ?

### ISSUE THREAD

**Issue by fulviocanducci** [sqlkata/querybuilder#17]
You could add support for .NET Standard 2.0 ?

**Comment by hey-red** [comment]
It's already supported.

**Comment by fulviocanducci** [comment]
You could change NetStandart to the current ???

![sd](https://user-images.githubusercontent.com/25593291/31312248-6b39f578-ab94-11e7-9034-af0fab4825bd.png)

**Comment by hey-red** [comment]
I actually think you are miss understood what netstandard.

**Comment by ahmad-moussawi** [comment]
yes as @hey-red mentioned, currently it works with netstandard2.0, **netstandard** is just a specification (where **netcore** or **netfx** are the implementation), and sqlkata meets those specs for both netstandard1.3 and 2.0.
plz correct me if I am wrong.

**Comment by hey-red** [comment]
Yep, its correct. 
You can use this library with all projects that targets .NET Standard >= 1.3, because .NET Standard 2.0 includes all API sets from 1.0, 1.1, 1.2, 1.3 etc.

**Comment by fulviocanducci** [comment]
I believe I have asked the wrong question, I'm sorry, how likely is this library to be updated with the version 2.0 netstandard, it being this version, because it would support many more platforms as an example below.

>![save123456-](https://user-images.githubusercontent.com/25593291/31355223-c71bf9be-ad0f-11e7-86b9-87eaefaf645e.png)

But if for some reason it's not okay ...

**Comment by ceastwood** [comment]
@fulviocanducci As others have mentioned, the .net framework versioning guidelines state that previous versions are supposed to be backwards compatible * for the most part *. 

For example, in the table you posted; A target framework of netstandard1.3 in this solution means that everything to the right of that column is implicitly supported. To the left would be unsupported.

 If you find some condition where it is not then that would be helpful to know. The goal is to target the least required set of framework implementation so that higher versions will just work.

Also if you were to require netstandard2.0 for some reason, you could very easily fork the repo, change the conditional rebuild files to netstandard2.0 and build yourself.

**Comment by fulviocanducci** [comment]
@ceastwood OK, no problem.
