### ISSUE TITLE
Pure functions?

### ISSUE THREAD

**Issue by corstian** [sqlkata/querybuilder#176]
While writing some stuff I figured that adding clauses cause updates to the root reference. From Entity Framework I'm kind of used that I can seamlessly assign the result of an operation (like adding a clause) to a new variable.

Is there a specific reason for not having pure functions or are you open to a PR containing some refactoring to have pure functions?

**Comment by corstian** [comment]
For anyone finding this; it's still possible to use the `.Clone()` method to get a copy of the instance.

**Comment by ahmad-moussawi** [comment]
What are the advantages of making it immutable ?

My reasons to not make it immutable are:
 - Every method should clone the query before modifying it and return back the cloned instance.
 - Huge memory consumption since everytime a new instance will get created
 - Some internal complication (We can work on this)

**Comment by corstian** [comment]
> "Every method should clone the query before modifying it and return back the cloned instance."

If I understand you correctly you are talking about implementing code, and not the library itself?

> "Huge memory consumption since everytime a new instance will get created"

Didn't think about that, thanks for pointing out!

I don't think it'd be worth it to change anything!
