### ISSUE TITLE
Declare InQuery Variables 

### ISSUE THREAD

**Issue by ahmad-moussawi** [sqlkata/querybuilder#184]
Add the ability to declare variables for the query especially when the variable is used more than once.

- Easier for debugging -> informative variable @date instead of  @p1, @p2, ....
- Enhance query abstraction, inner queries can assume that some variable are declared without the need to pass variable in C# code.

```cs
db.Query("Balances")
.WithVar("date", DateTime.UtcNow)
.WhereRaw("[ValueDate] > @date")
.WhereRaw("[ValueDate] < @date")
```

**Comment by naergaga** [comment]
Simple implementation：
```csharp
public partial class Query : BaseQuery<Query>
{
    public Dictionary<string, object> VarMap { get; set; } = new Dictionary<string, object>();
    public Query WithVar(string parameterName, object parameterValue)
    {
        VarMap.Add(parameterName, parameterValue);
        return this;
    }
}

public partial class Compiler
{
    public virtual SqlResult Compile(Query query)
    {
        var ctx = CompileRaw(query);

        ctx = PrepareResult(ctx);

        foreach (var item in query.VarMap)
        {
            ctx.NamedBindings.Add(item.Key, item.Value);
        }
        return ctx;
    }
}

```
It takes a lot of work to be fully usable.

**Comment by mota57** [comment]
@ahmad-moussawi  Please take a look when you have a chance.

**Comment by mota57** [comment]
@ahmad-moussawi this could work with MysQL, SQLServer, PostgreSQL.

 I already have the code to build just the declaration part for MySQL, SQL Server, and SQLite but the challenge would be the Where conditions. Let's review how can we generate the SQLite and PostgreSQL.

Base on this answer https://stackoverflow.com/questions/7739444/declare-variable-in-sqlite-and-use-it
if we want to use this feature for sqlite we will have to write the code like in the listing 1.1

Listing 1.1

```
CREATE TEMP TABLE Variables (Name TEXT PRIMARY KEY, Value TEXT);
INSERT OR REPLACE INTO Variables VALUES ('var1', 'account 1');

SELECT *
FROM accounts WHERE name =  (SELECT  Value FROM Variables where Name = 'var1')
```

There are multiple functions in sqlkata that are responsible to build the part of the where clause depending on what type of Where clause you use and as you see this will require more time to build it for SQLite.

For postgresSQL there is a way to build declarations, I didn't test it but base on this [answer ](https://stackoverflow.com/questions/1490942/how-to-declare-a-variable-in-a-postgresql-query) we can use something like in the listing 1.2

```
WITH myconstants (var1, var2) as (
   values (5, 'foo')
)
SELECT *
FROM somewhere, myconstants
WHERE something = var1
   OR something_else = var2;
```

For this task, as you saw previously like in SQLite will require some time because I have to modify the code relates to the WhereConditions clause

**Comment by for7raid** [comment]
Hi @ahmad-moussawi 
In PR #184 you turned into this code 
```
DECLARE @date DATETIME = ?
SELECT * FROM [Table] WHERE [Date] = @date;
```

but why you want to declare the inline var in raw sql and get very platform specific code?

I hope, that we need only replace 'unnamed' @p... params to named in binding collection,
so code
```
new Query("Table")
  .WithVar("@date", DateTime.UtcNow)
  .Where("Date", "@date")
```
should be compiled on every platform to
```
SELECT * FROM [Table] WHERE [Date] = @date;
```
with bindings collection is [{@date, 2019-05-08 12:10:00}]

**Comment by ahmad-moussawi** [comment]
@mota57 thank you for the informative research, as you've mentioned Oracle, SQLite and Postgres seem that they don't support a direct way of variable declaration, and the provided solutions would add unwanted complexity.

so sticking to the previous approach you were working on is the best for now (same example provided by @for7raid).

**Comment by mota57** [comment]
Ok as @for7raid I think might replace @px and I did that for a simple query. You can see the results in the picture, but I will have to test each function at Compiler.Condition.cs to make sure it works for every case.

```
var query = db.Query("Products")
              .WithVar("@name", "Chai")
              .Where("ProductName", "@name");
```


![image](https://user-images.githubusercontent.com/7569989/57409171-a1dac880-71b5-11e9-9736-dea294935a93.png)

**Comment by mota57** [comment]
@for7raid one question if we avoid using the declaration how I am supposed to implement this with the method "WhereRaw"?

**Comment by for7raid** [comment]
@mota57 your last picture is not I mean
My opinion that WithVar function should only add variable to bindings collection, nothing more. Then your can use this var in any part of the query, even in raw clause. No slq "declaration" needed. 

```
var query = db.Query("Products")
              .WithVar("@name", "Chai")
              .WithVar("@date", DateTime.Now)
              .Where("ProductName", "@name")
              .WhereRaw("@date between [SaleStart] and [SaleEnd]");
```
goes to
```
select * from [Product] where [ProductName] = @name and @date between [SaleStart] and [SaleEnd]
```
and compile returns binsings
``[{@name, "Chai"}, {@date, 2019-05-09}]``

**Comment by mota57** [comment]
@for7raid thanks for the information I did some changes based on what you said, I add the variables to the binding property,  I removed the declaration part,   I tested what I have with methods like WhereIn, WhereRaw, Where, OrWhere, WhereIn<string> and with nested conditions. So, it works but I have to make a couple more changes and complete the test cases in order to upload a new branch.

**Comment by ahmad-moussawi** [comment]
@mota57 amazing, if you need any help/assistance let us know.

**Comment by mota57** [comment]
@ahmad-moussawi ready

**Comment by ahmad-moussawi** [comment]
@mota57 thanks for the update, appreciate it, I will review it soon and get back to you

**Comment by mota57** [comment]
Any news about this ?

**Comment by naergaga** [comment]
MyCode:
```csharp
```

@ahmad-moussawi In the `result.ToString()` method, there is still `@variable`, maybe it can be better.
```sql

 ```

**Comment by naergaga** [comment]
My Code:
var q1 = new Query("Posts").WhereRaw("Id=@Id").Define("Id", 1);

**Comment by timbze** [comment]
I'm curious if there's any update on this?

**Comment by mota57** [comment]
no idea, I remember I move my code by never went to production.

**Comment by ahmad-moussawi** [comment]
Actually it's available in the latest prerelease.
Working on the documentation before the official release.
A big thanks for @mota57

**Comment by mota57** [comment]
oh i didnt know that, thanks for letting me know.

**Comment by brgrz** [comment]
So this was never merged? I see no traces of WithVar() anywhere in the api. Was there ever another way introduced?
