### ISSUE TITLE
Just get RAW SQL

### ISSUE THREAD

**Issue by jbpatelgit** [sqlkata/querybuilder#195]
Is there any method to get entire RAW SQL? I don't want to execute it.

**Comment by ahmad-moussawi** [comment]
https://sqlkata.com/docs#compile-only-example

**Comment by jbpatelgit** [comment]
> https://sqlkata.com/docs#compile-only-example

Thanks for the quick response. Would Compile()  actually try to compile the query? I know it won't compile in my case because of the type of home grown DB engine we use.

**Comment by ceastwood** [comment]
@jbpatelgit I'm not quite sure how to help--

To get the raw SQL in any case, you need to compile the query object against one of the compilers like described by @ahmad-moussawi. If you were truly using a custom db engine, you wold need a custom compiler so that it could adhere to the syntax and language of that engine.

I'll go out on a limb and say that you could likely use one of the ones included to get your result. For example, you could use the SqlServer compiler, get the sql and paste into SQL Management to verify, etc.
