### ISSUE TITLE
What is is with the ToString() Warning?

### ISSUE THREAD

**Issue by psylithic** [sqlkata/querybuilder#252]
Hey there,

There's a warning in the [supporting documentation ](https://sqlkata.com/docs/#compile-only-example)that says the following:
![image](https://user-images.githubusercontent.com/583568/57483773-289eac80-726d-11e9-9ebb-22f163ed985d.png)

What does that mean and why is the warning in place? Looking at the implementation, it seems like it generates a string with all of the parameters filled in with set Bindings... which is the desired behavior. (A query that could just be copy-pasted directly into SSMS and be ran, for example)

**Comment by for7raid** [comment]
hello @psylithic 
it is because of culture in ToString method.
ToString method creates the sql by converting variables (sql arguments) depend on culture on your local machine, what can be incompatible with sql server parse settings depend on server culture. It is about DateTime, double and float data types.
You have to use only compile result with raw sql and bindings, and ADO should combine it in right way.
ToString just for debugging.

**Comment by ahmad-moussawi** [comment]
in addition to what @for7raid said, you will be open for **SQL injection** and lose the query plan caching mechanism when using **ToString()** to execute your queries within the app, using it for debugging purposes is totally fine.

**Comment by psylithic** [comment]
Thanks.
