### ISSUE TITLE
OrWhere Doesn't Work

### ISSUE THREAD

**Issue by curruwilla** [sqlkata/querybuilder#286]
Query:
```
var search = "%" + SearchText + "%";
db.Query()
                .Where("name", "like", search)
                .OrWhere("reference", "like", search)
                .WhereFalse("deleted")
                .Get();
```

**Comment by ahmad-moussawi** [comment]
What do you mean by doesn't work?

**Comment by curruwilla** [comment]
Run this query I passed above, it doesn't work, using OrWhere, WhereFalse doesn't work... I do not know why..

**Comment by ahmad-moussawi** [comment]
Are you getting an exception, getting wrong data, failed to compile ?
A side note you can use `WhereContains` instead of `Where(col, "like", value)` check https://sqlkata.com/docs/where-string

Another thing always wrap the "or" conditions because they will be logically grouped at the same level as other conditions like you did in the another example.

**Comment by curruwilla** [comment]
Your Sqlkata library is TOP, maybe I don't know how to use it, I could make it work already, thanks :)
Don't abandon this project is helping a lot!!
Maybe to motivate you, add a paypal contribution link!
Sorry english, i am brazilian and i use google translator
good job

**Comment by ahmad-moussawi** [comment]
Thanks @curruwilla, happy that it helps you
