### ISSUE TITLE
string with only number is transform to int 

### ISSUE THREAD

**Issue by AlainDessi** [sqlkata/querybuilder#29]
If I do 

.Update(
  new[] { "myColumn" },
  new object[] { "090" }
);

after compile I get 
UPDATE `my_table` SET `myColumn` = 090 

is a problem for me.
In my case, MyColumn is a Char(3)

**Comment by ahmad-moussawi** [comment]
Actually the `.ToString()` method tries it's best to guess the params type, in order to just display them form debugging purposes, so **you should not use it to execute your queries**, you should use the `.Sql` property instead.

so your queries will get executed correctly regardless of how they get displayed.

**Comment by AlainDessi** [comment]
Thanks,
Compile.Sql and Binding work's fine ...
