### ISSUE TITLE
Unexpected "ORDER BY (SELECT 0)" inside SELECT query - Oracle Compiler

### ISSUE THREAD

**Issue by artemiusgreat** [sqlkata/querybuilder#305]
Hi, the simplest query adds some unexpected "ORDER BY (SELECT 0)" in the middle of it.
Is it expected behavior for OracleCompiler or a known bug? 

```
var compiler = new OracleCompiler();
var queryFactory = new QueryFactory(DBConnection, compiler);
var query = queryFactory.Query("MyTable").Limit(10); // also tried Take(10)

var SQL = queryFactory.Compiler.Compile(query); 
// SELECT * FROM "MyTable" ORDER BY (SELECT 0) OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

var items = query.Get();  
// Exception ORA-00923: FROM keyword not found where expected
```

**Comment by abcdef434** [comment]
same failue on me........

**Comment by ahmad-moussawi** [comment]
It seems this behavior is copied from SqlServer compiler as is,  and Oracle does not allow **select** statement without the **from** clause.

One solution could be using the **FROM DUAL**
```
select * from table order by (select 1 from dual) offset <X> rows fetch next <Y> rows only;
``` 
or even without the order by clause since it is not required (like in SqlServer) https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqljoffsetfetch.html

So the suggested solution should be 
```
select * from table offset <X> rows fetch next <N> rows only;

**Comment by ahmad-moussawi** [comment]
@artemiusgreat @abcdef434 fixed in the latest release, you can use the nightly build for now
