### ISSUE TITLE
AsMax when result is NULL

### ISSUE THREAD

**Issue by JordiPerello** [sqlkata/querybuilder#439]
Hi,

I use SqlKata to create my queries and I use Dapper to send these rendered queries

In SqlKata, when I use "AsMax" clause, my query is the following "SELECT MAX (column) FROM Table",
and when I pass this query to Dapper, in some cases the Dapper query result is NULL, because it finds no records in the table
The solution to this problem is to create said query as follows "SELECT ISNULL (MAX (column), 0) FROM Table"
I have created an "AsMax" wrapper, in which I manipulate the query to make it work, but it would be convenient if SqlKata itself had an overload of this "AsMax" method, which uses the "ISNULL ()"

**Comment by ahmad-moussawi** [comment]
We try to avoid as much as possible the extra manipulation was done implicitly by SqlKata, and in future versions, we are planning to remove some also, keeping SqlKata transparent will serve its purpose more, in this case, `0` and `NULL` have a different meaning why not `-1` or `-Infinity` etc...

I think a better way may be to handle this in C# or in a custom extension that meets your needs.

Out of curiosity why you are not using the `SqlKata.Execution` package to execute your queries instead of dealing with dapper directly?
