### ISSUE TITLE
If you get after insert, the same data will be inserted twice.

### ISSUE THREAD

**Issue by ikuosaito1989** [sqlkata/querybuilder#482]
Hi.

If you put Query into a variable and execute Insert and Get in turn, two identical data will be inserted.

An example of two data being inserted is shown below.

```c#
var query = _db.Query("Tables");
var id = query.InsertGetId<int>(raw);
var models = query.Where("Id", id).Get<Tables>();
```

When executing without putting the data in a variable, only one data will be inserted. This behavior is correct.

An example of a single data being inserted is shown below.

```c#
var id = _db.Query("Tables").InsertGetId<int>(raw);
var models = _db.Query("Tables").Where("Id", id).Get<Tables>();
```

**Comment by asherber** [comment]
It's important to remember that `Query` objects are not immutable; if you call a method on `Query`, it changes the object you pass in. So, for example, if you have a `Query` variable `q`, then `q = q.Where("foo", "bar")` and `q.Where("foo", "bar")` do exactly the same thing -- you wind up with a `WHERE` clause attached to `q`.

In this case, if you look at [the code](https://github.com/sqlkata/querybuilder/blob/b762ed996091abbe599e68c2b4fbab7752bf2763/SqlKata.Execution/Query.Extensions.cs#L197) for `InsertGetId()` you'll see that the method calls `query.AsInsert()`, which turns the object you pass in into an `INSERT` query. When you call `Get()` after that, the query is still an `INSERT` query and is compiled that way.

In your second example, since you're not persisting the `Query` object, your two lines of code use two different transient `Query` objects.

If you want to do things the first way (build up part of a base query that you can reuse), you need to use `Clone()` to create copies of your base query, rather than just reusing the base. So the following works:

```c#
var query = _db.Query("Tables");
var id = query.Clone().InsertGetId<int>(raw);
var models = query.Clone().Where("Id", id).Get<Tables>();
```

(I admit that this is the one major design thing that I wish SqlKata did differently -- I wish that each fluent method call returned a new object, leaving the original object alone. In that case, your first code example would work as expected.)

**Comment by ikuosaito1989** [comment]
@asherber 

`Query` objects turned out to be the right move, thanks!

Do you know where the documentation for the `Clone` method can be found?

**Comment by asherber** [comment]
Clone: https://sqlkata.com/docs/advanced#clone

**Comment by ikuosaito1989** [comment]
@asherber 
Thanks! That was helpful!
