### ISSUE TITLE
Forcing return type when initiating a select query

### ISSUE THREAD

**Issue by dom3551-git** [sqlkata/querybuilder#483]
Hi, rather than using the generic overload on the Get method to return a strongly typed result, would it be possible to set the return type when initialising the query....so something like

`var products = db.Query<Product>("Products")`

This would allow me to embed initialising the query into a Repository class method with the database table name and typed result set automatically, something like...

`class Product 
{
     public Query<Product> GetProducts()
     {
                return db.Query<Product>("Products");
     }
}`

Once the query is executed, it then returns the typed set automatically.....

**Comment by dom3551-git** [comment]
The above seemed to strip out the generic setting I added to the statement...should read...

`var products = db.Query<Product>("Products")`

and 

`class Product
{
          public Query<Product> GetProducts()
          {
                    return db.Query<Product>("Products");
          }
}`

**Comment by ahmad-moussawi** [comment]
This wont work for queries with custom selections, check #183

**Comment by dom3551-git** [comment]
Thanks for coming back to me Ahmad – it certainly looks like what I need. However, building a .Net Core application, I’m currently using DI and your QueryFactory to generate new queries for me and I’m not sure how to get your factory to return me an instance of the GenericQuery instead of the standard SQLKata query…..any thoughts welcome! 😊

Dominic

**Comment by springjazzy** [comment]
@dom3551-git It seems that it's impossible to return strongly-typed Query. But its often needed for `IQueryable<T>` Repository. One possible solution would be to return `IEnumerable<T>` (or even `T[]` since in case of `IEnumerable<T>` connection may be leaked - lazy execution) and parametrise Repository with [Specification](https://en.wikipedia.org/wiki/Specification_pattern) pattern.  In `Specification` you can put all business-logic, give it meaningful name and pass to repository.
