### ISSUE TITLE
Compare DateTimes with full precision?

### ISSUE THREAD

**Issue by ntwilson** [sqlkata/querybuilder#587]
When compiling a DateTime in a select query, it only goes out to the second.  Is there a reason not to include the full precision of the DateTime when compiling?  I can just add/subtract a second to achieve the results I desire, but it's easy to forget the need to do so whenever comparing DateTimes.

Thanks!

**Comment by ahmad-moussawi** [comment]
SqlKata (in most cases) don't intercept and changes the values passed to the database, it only passes them as parameters, I  think what you faced is when using the `.ToString()` method, which try it's best to represent the value as string, and this is **only** for debugging purposes, and should not be used for executing queries.

**Comment by ntwilson** [comment]
You can see in the SqlKata Playground that if you include a DateTime in a query, it will only include up to the second precision:
![image](https://user-images.githubusercontent.com/15835006/179430094-0af98a4b-5a5e-4293-bb88-da226d5fac7b.png)

This is even the case if you set the current culture to print full precision through the `.ToString()` method:
![image](https://user-images.githubusercontent.com/15835006/179430169-bd901b03-8b09-4b75-a5fd-bc5ce9039679.png)

I'm pretty sure this happens in QueryBuilder/SqlResult.cs (63-71), where it says
```C#
            if (value is DateTime date)
            {
                if (date.Date == date)
                {
                    return "'" + date.ToString("yyyy-MM-dd") + "'";
                }

                return "'" + date.ToString("yyyy-MM-dd HH:mm:ss") + "'";
            }
```
It seems that behavior is hard-coded in...

**Comment by ahmad-moussawi** [comment]
Yes that's the intended behavior when using the `ToString()` method which is used in Playground as mentioned above for debugging purposes, but this is not the case for the real query executed against the database.

so here to answer your question, why the format is hardcoded to the seconds, since this is most conventional for most use cases, since printing all the seconds fractions is more verbose and not needed in most cases.

as a workaround you can pass the values as string as you did in your example.

if you really see that this should be included, we may discuss adding it as an optional flag.
