### ISSUE TITLE
Refactor DynamicCompile

### ISSUE THREAD

**Issue by Happi-cat** [sqlkata/querybuilder#76]
Currently it uses reflection for method selection for each condition clause (every type and instance).
And it do same things every time (i.e. find method & invoke it) for same condition types without caching.

Possible solns:
* visitor pattern
* cached compiled expressions

Visitor pattern is trivial

**Comment by ahmad-moussawi** [comment]
agree, actually I am planning to refactor how the compiler works, by taking expressions (Binary Expressions, Literal Expressions, etc ...) instead of static clauses, that makes extending the library more easier, and supporting more features (like sql functions, when cases expression and so on)

then I can rebuild the existing methods on top of the low level expressions.

**Comment by Happi-cat** [comment]
are u going to keep same public API and use expression beneath or will adding of expressions require breaking API changes?

**Comment by ahmad-moussawi** [comment]
Yes most of the methods will have the same public api, so no major breaking changes here, but 
string and date operations may be removed in future releases `whereStarts`, `whereEnds`, `whereContains`, and `whereDateX` methods, since using expressions is more generic in this case.
